version: '3.8'
services:
  postgres:
    container_name: postgres_python_scrapy
    image: postgres:10.5

    env_file:
      - .env
    restart: always
    ports: 
      - "5435:5432"
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    # copy the sql script to create tables
    #   - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    # # copy the sql script to fill tables
    #   - ./sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
volumes:
  postgres_data:
  